nohup ./run_scripts/run_desktop_P04.sh > /mnt/d/3_case_SPRUCE_data_analysis/2_TECO-SPRUCE_data_assimilation/5_TECO-SPRUCE_v3_DA/1_outputs/outlogs/out_P04.log &
nohup ./run_scripts/run_desktop_P06.sh > /mnt/d/3_case_SPRUCE_data_analysis/2_TECO-SPRUCE_data_assimilation/5_TECO-SPRUCE_v3_DA/1_outputs/outlogs/out_P06.log &
nohup ./run_scripts/run_desktop_P08.sh > /mnt/d/3_case_SPRUCE_data_analysis/2_TECO-SPRUCE_data_assimilation/5_TECO-SPRUCE_v3_DA/1_outputs/outlogs/out_P08.log &
nohup ./run_scripts/run_desktop_P10.sh > /mnt/d/3_case_SPRUCE_data_analysis/2_TECO-SPRUCE_data_assimilation/5_TECO-SPRUCE_v3_DA/1_outputs/outlogs/out_P10.log &
nohup ./run_scripts/run_desktop_P11.sh > /mnt/d/3_case_SPRUCE_data_analysis/2_TECO-SPRUCE_data_assimilation/5_TECO-SPRUCE_v3_DA/1_outputs/outlogs/out_P11.log &
nohup ./run_scripts/run_desktop_P13.sh > /mnt/d/3_case_SPRUCE_data_analysis/2_TECO-SPRUCE_data_assimilation/5_TECO-SPRUCE_v3_DA/1_outputs/outlogs/out_P13.log &
nohup ./run_scripts/run_desktop_P16.sh > /mnt/d/3_case_SPRUCE_data_analysis/2_TECO-SPRUCE_data_assimilation/5_TECO-SPRUCE_v3_DA/1_outputs/outlogs/out_P16.log &
nohup ./run_scripts/run_desktop_P17.sh > /mnt/d/3_case_SPRUCE_data_analysis/2_TECO-SPRUCE_data_assimilation/5_TECO-SPRUCE_v3_DA/1_outputs/outlogs/out_P17.log &
nohup ./run_scripts/run_desktop_P19.sh > /mnt/d/3_case_SPRUCE_data_analysis/2_TECO-SPRUCE_data_assimilation/5_TECO-SPRUCE_v3_DA/1_outputs/outlogs/out_P19.log &
nohup ./run_scripts/run_desktop_P20.sh > /mnt/d/3_case_SPRUCE_data_analysis/2_TECO-SPRUCE_data_assimilation/5_TECO-SPRUCE_v3_DA/1_outputs/outlogs/out_P20.log &